### PR TITLE
Add Gazebo model for Swan-K1-HWing

### PR DESCRIPTION
**Pull request by srmainwaring**
This draft PR adds a Gazebo model for the Swan-K1-HWing

Figure: Swan-K1 in forward flight. Updated so user content available to reference in model documentation.

swan-k1-hwing-flying

## Usage

Ignition and the plugins should be installed as per the [ardupilot_gazebo wiki instructions](https://github.com/ArduPilot/ardupilot_gazebo/wiki).

#### Run Gazebo

```bash
$ gz sim -v4 -r swan_k1_hwing_runway.sdf
```

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@srmainwaring ready to merge? maybe squash the commits?

**Comment by srmainwaring** [comment]
@tridge let me take a look - it's been a while. I marked this as draft for some reason and will need to recall why?

**Comment by srmainwaring** [comment]
Still an issue with the stability - it appears similar to the problem I have with the Gazebo model for the Omnicopter. It may be due to the prop modelling - where thrust is generated by treating the rotors as lifting surfaces and applying the lift and drag forces directly to the rotor links. This does cause noise in the joints and that may be more of an issue for certain frame configurations - it is hard to pin down.

An alternative approach is to calculate the prop thrust and torque directly and apply this to the motor links. The rotor spinning is then for visualisation only, not for physics. There is a plugin available in the upstream gz-sim7 package that is similar to the original RotorS plugin - will investigate whether applying this results in a flyable model.

**Comment by srmainwaring** [comment]
@tridge - I'll merge this as I've resolved the main issue with the prop model. It's flying with a large AoA in forward flight - which could be resolved by increasing the cruise speed, but I think the real issue is more likely to be short comings in the aerodynamics model. It's operational though, tuned with the Lua VTOL script and running the onboard FFT notch filter - so a nice test ground for a few newer features.

**Pull request merged**
