### PR TITLE
Add the Aion R1 rover model 

### PR DESCRIPTION
**Pull request by itskalvik**
@srmainwaring Taking option 2. I made a new branch and made a PR from that.

aion_r1_gz_sim

**Usage**

Gazebo and the plugins should be installed as per the [ArduPilot Gazebo Plugin](https://github.com/ArduPilot/ardupilot_gazebo) instructions.

Update the GZ_SIM_RESOURCE_PATH to include these models:

`
export GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH:\
$HOME/SITL_Models/Gazebo/models:\
$HOME/SITL_Models/Gazebo/worlds
`

**Run Gazebo**

`
gz sim -v4 -r r1_rover_runway.sdf
`

**Run ArduPilot SITL**

`
sim_vehicle.py -v Rover -f JSON --add-param-file=$HOME/SITL_Models/Gazebo/config/r1_rover.param --console --map
`

### CODE REVIEW

**Comment by srmainwaring** [comment]
@itskalvik - thanks for the contribution. I've pushed the edits discussed in #120. Could you please review and let me know if you're happy with the changes.

The command I'm using to start SITL is:

```bash
sim_vehicle.py -v Rover -f rover-skid --model JSON --add-param-file=$HOME/SITL_Models/Gazebo/config/r1_rover.param --console --map
```

which highlights that the starting point is the `rover-skid` config.

Adjusting the follow camera gives a better view of the wheel slip in turns:

```bash
gz service -s /gui/follow/offset --reqtype gz.msgs.Vector3d --reptype gz.msgs.Boolean --timeout 2000 --req "x: -0.5, y: 0.5, z: 0.5"
```

**Comment by itskalvik** [comment]
This is incredible! You went way and beyond what I was expecting 🤯 Thank you So much for your work and quick response!! 😊

**Comment by jmachuca77** [comment]
Unfortunately these repos have been made private. I would try contacting AION directly to see if the can be reopened.

**Comment by srmainwaring** [comment]
@itskalvik - added a user guided and squashed. I've sent AION an email asking about the license and access to original models. Will wait for their reply before merging, although with the PX4 model public this should not be an issue.

**Pull request merged**
