### PR TITLE
Add model for Hexapod Copter

### PR DESCRIPTION
**Pull request by srmainwaring**
This PR is for an experimental frame combining a hexapod and hexacopter.

hexapod_copter_hover

The frame is fully articulated. Each of the 6 legs has 3 joints, however only 16 are actuated. The middle two 'hip' joints are fixed in this example. The motor ordering and orientation is the same as a standard hexa X frame, however in this case the `FRAME_CLASS 17 (Dynamic Scripting Matrix)` and the motor mixing is set in the Lua script.

The legs have two positions - folded when disarmed, and unfolded when armed.

If the scripting control of the legs is disabled they may be moved using `gz topic` commands:

```bash
# move the mid right femur joint down from its initial position of -0.6 rad to -0.4 rad 
gz topic -t "/femur_mr_joint/cmd_pos" -m gz.msgs.Double -p "data: -0.4"
```

## Dependencies

The hexapod copter requires 32 servo support and has upstream dependencies on these PRs:

- https://github.com/ArduPilot/ardupilot/pull/23239
- https://github.com/ArduPilot/ardupilot_gazebo/pull/49

## Usage

Gazebo and the plugins should be installed as per the [ArduPilot Gazebo Plugin](https://github.com/ArduPilot/ardupilot_gazebo) instructions.

Update the `GZ_SIM_RESOURCE_PATH` to include these models:

```bash
export GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH:\
$HOME/SITL_Models/Gazebo/models:\
$HOME/SITL_Models/Gazebo/worlds
```

#### Run Gazebo

```bash
gz sim -v4 -r hexapod_copter_runway.sdf
```

#### Run ArduPilot SITL

Copy the script `$HOME/SITL_Models/Gazebo/scripts/hexapod_copter.lua` to the SITL scripts directory,
then start SITL:

```bash
sim_vehicle.py -D -v ArduCopter -f hexa --model JSON --add-param-file=$HOME/SITL_Models/Gazebo/config/hexapod_copter.param --console
```

### CODE REVIEW

**Comment by davidbuzz** [comment]
i love the pr... great start.. it was my hope that lua would b able to move the leg actuators as normal servos[like the motors].. is that possible?

**Comment by srmainwaring** [comment]
@davidbuzz added a quadruped copter version which is configured for scripting. The scripts folder has an example script `quadruped_copter.lua` and there are params in `config/quadruped_copter.param` which extend the standard quad params.


#### Run Gazebo

```bash
gz sim -v4 -r quadruped_copter_runway.sdf
``` 

#### Run SITL

First `quadruped_copter.lua` to the ardupilot scripts directory. Then run SITL:

```bash
sim_vehicle.py -D -v ArduCopter -f quad --model JSON --console --add-param-file=<path_to_quadruped_copter.param>
```

The script is only partially working. The legs set to the disarmed position, but the motors don't spin and the vehicle wont arm because it's expecting motor mappings - need to figure the correct FRAME_CLASS etc. for scripting.

**Comment by davidbuzz** [comment]
Wow.

**Comment by srmainwaring** [comment]
There is a working version of the hexapod_copter in https://github.com/ArduPilot/SITL_Models/pull/96/commits/e51a5810d1094c75acbb44fc0a6192b45e1be16a.

It follows the same approach as the quadruped_copter with:

- FRAME_CLASS 15 (Scripting Matrix)
- FRAME_TYPE 1 (Scripting Matrix)
- SERVO_32_ENABLE  1
- SERVOX_FUNCTION X = 1 - 6 are standard motors (33, 34, 35, 36, 37, 38)
- SERVOX_FUNCTION X = 7 - 22 are scripting (98, 99, ..., 109)
- The MotorMatrix was derived from the settings in `AP_MotorsMatrix::setup_hexa_matrix` for `MOTOR_FRAME_TYPE_X`
- Two mid joints are not actuated, because scripting presently only supports 16 servo assignments using SERVOX_FUNCTION.

### Dependencies

There are two small changes needed to support 32 servos in SITL_JSON and the ArduPilot Gazebo plugin. They are in these commits:

- https://github.com/ArduPilot/ardupilot/commit/c98489e81a1c23c442c7a7cc610fdd0006344ac3
- https://github.com/ArduPilot/ardupilot_gazebo/commit/d8ddccd7931837052c516059f38b911166d79b24

**Comment by davidbuzz** [comment]
cd ~/gazebo/

mkdir ./scripts
cp ./SITL_Models/Gazebo/scripts/hexapod_copter.lua ./scripts

from gazebo plugin prior to updating it:

[Err] [ArduPilotPlugin.cc:1487] [hexapod_copter] control[19] channel [19] is greater than the number of servo channels [16], control not applied

and then on a later attempt..

[Wrn] [ArduPilotPlugin.cc:1386] Incorrect protocol magic 29569 should be 18458
[Wrn] [ArduPilotPlugin.cc:1386] Incorrect protocol magic 29569 should be 18458
[Wrn] [ArduPilotPlugin.cc:1386] Incorrect protocol magic 29569 should be 18458
[Wrn] [ArduPilotPlugin.cc:1386] Incorrect protocol magic 29569 should be 18458


and then after a rebase and clean build of the gazebo plugin, it stopped throwing those errors, and then the arducopter console started giving me this:

No JSON sensor message received, resending servos
No JSON sensor message received, resending servos
No JSON sensor message received, resending servos
No JSON sensor message received, resending servos
No JSON sensor message received, resending servos

 so i tried a 'rm -rf ./build/sitl/' before running sim_vehicle again, but no difference.


i was/am unable to get the sim_vehicle.. + gz sim..   combo to talk to each other..  I'm clearly doing something wrong.


---------------------------
~/gazebo/ardupilot_gazebo$ git status
On branch srmainwaring/garden/pr-servo-32-enable
Your branch is up to date with 'srmainwaring/srmainwaring/garden/pr-servo-32-enable'.

nothing to commit, working tree clean
---------------------------
~/gazebo/SITL_Models$ git status
On branch srmainwaring/hexapod-copter
Your branch is up to date with 'srmainwaring/srmainwaring/hexapod-copter'.

nothing to commit, working tree clean
---------------------------
~/ardupilot$ git status
On branch pr-sitl-servo-32-enable
Your branch is up to date with 'srmainwaring/pr-sitl-servo-32-enable'.

nothing to commit, working tree clean

**Review by davidbuzz — APPROVED** [review]
ca confirm i have tested and reviewed this, and together with the other two PR's, it does what it says on the tin... ie  it flies a 6-legged, 6 propped, hexapod/hexacopter in gazebo, which can be flown around like a hexa after arming.

**Comment by davidbuzz** [comment]
should the 20-ish commits be squashed down, and the [presumably no longer relevant] "iris" files be removed before its merged..?

**Comment by srmainwaring** [comment]
> should the 20-ish commits be squashed down, before its merged..? - not a big deal either way, in my opinion, but the quadruped copter could be its own commit[ or dropped, now that the hexa variant fully works, up-to-you? ]

Yes, I'll drop the quad version as it was mainly to get up and running b4 the 32 servo changes were added. Will squash the remainder down to a single commit.

**Pull request merged**
