### PR TITLE
Add truck quadplane landing example

### PR DESCRIPTION
**Pull request by srmainwaring**
This draft PR provides an example for simulating a quadplane landing on the back of a truck semi-trailer unit.

It has a dependency on https://github.com/ArduPilot/SITL_Models/pull/61 which is cherry-picked into this PR. When #61 has been merged this PR can be rebased and moved to review.

https://user-images.githubusercontent.com/24916364/151050925-e33c7441-7e68-430f-9622-8ddd8b7f61f3.mov

## Usage

You must run the SITL launch script **before** starting Ignition Gazebo as it generates the world file for the simulation.

**Run ArduPilot SITL**

Change to the root directory where ArduPilot is installed (`$ARDUPILOT_HOME`), then run the launch script:

```bash
~/SITL_Models/Ignition/launch/truck-quadplane-landing.sh
```

This will create a number of directories under the ardupilot root directory. There is a directory for each vehicle that contains the `eeprom.bin` for each SITL instance, additional parameter files for configuring the `SYSID_THISMAV` and follow mode. For the tractor unit there is also a scripts directory containing the custom mixer.

The `worlds` directory contains a generated SDF world file that configures each model to have the correct ports and assembles the tractor - trailer units from their component parts.

```
sitl
├── quadplane
│   ├── eeprom.bin
│   ├── follower.param
│   ├── logs
│   │   ├── 00000001.BIN
│   │   └── LASTLOG.TXT
│   └── terrain
│       └── S36E149.DAT
├── tractor
│   ├── eeprom.bin
│   ├── leader.param
│   ├── logs
│   │   ├── 00000001.BIN
│   │   └── LASTLOG.TXT
│   └── scripts
│       └── daf_xf_450_tractor_mixer.lua
├── trailer
│   ├── eeprom.bin
│   ├── leader.param
│   └── logs
│       ├── 00000001.BIN
│       └── LASTLOG.TXT
└── worlds
    └── truck_quadplane_landing.sdf
```

**Run Gazebo**

```bash
ign gazebo -v 4 -r truck_quadplane_landing.sdf
```

**Run MAVProxy**

In another terminal run the `MAVProxy` launch script supplying as an argument the number of vehicles being simulated:

```bash
~/SITL_Models/Ignition/launch/mavproxy-multi-vehicle.sh 3
```

Enable position forwarding:

```
MAV> set posfwd 1
```

**Controlling the vehicles**

There are 3 vehicles:

- `vehicle 1` is the truck tractor unit. This can be set to follow a mission in auto mode.
- `vehicle 2` is the truck trailer unit. It is configured as a rover, but does not respond to commands and exists to publish the position of the trailer CoM which will generally have a different pose (position + yaw) and twist (angular and linear velocity) to the tractor unit.
- `vehicle 3` is the quadplane which is initially situated on the trailer unit just behind the CoM.

## Notes

The truck is speed limited to 5 m/s in AUTO mode by overriding `WP_SPEED` in the launch script.

The quadplane model is now an Alti Transition QuadPlane

The [MAVProxy wiki](https://ardupilot.org/mavproxy/index.html) contains more information about using SITL with multiple vehicles:
 
- [Multi-Aircraft SITL with MAVProxy](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#multi-aircraft-sitl-with-mavproxy)
- [Multiple Vehicles with MAVProxy](https://ardupilot.org/mavproxy/docs/getting_started/multi.html#multiple-vehicles-with-mavproxy)

### CODE REVIEW

**Comment by JohnVorwald** [comment]
I tried to switch 3rd vehicle from alti to iris, and the iris model doesn't connect to mavproxy.  How to debug / resolve?

**Comment by srmainwaring** [comment]
> I tried to switch 3rd vehicle from alti to iris, and the iris model doesn't connect to mavproxy. How to debug / resolve?

Hi @JohnVorwald, it's customary not to add help requests to closed issues and PRs. The best place to ask for help is ArduPilot Discourse. Can you open a request there, provide details of your environment and what you are trying to do. The more information (details of commands, code changes), the more likely it is someone will be able to reproduce and help.

**Comment by JohnVorwald** [comment]
Good morning, @srmainwaring .  I described the error here: 
https://discuss.ardupilot.org/t/combine-two-working-models-for-gz-sim/111313/3

**Comment by YonggilKwon** [comment]
Hello, I use gazebo harmonic and this is an environment of uvuntu 22.04. I'm going to test the above, so I don't move my home point with the message no beacon. Is there a solution?

**Comment by MustafaSari1** [comment]
I have same issue with @YonggilKwon . (Ship: No beacon)

I am trying to solve.

**Comment by MustafaSari1** [comment]
> MAV> set posfwd 1

I could not understand this. How can I complete this step @srmainwaring

**Comment by srmainwaring** [comment]
@MustafaSari1, please see the comments above. There is a link to a discourse thread in the reply where the original request was resolved. If you need additional help please post bin logs and terminal outputs as text (in discourse not here) as these are more useful when analysing issues.

**Comment by MustafaSari1** [comment]
> I have same issue with @YonggilKwon . (Ship: No beacon)
> 
> I am trying to solve.



> > MAV> set posfwd 1
> 
> I could not understand this. How can I complete this step @srmainwaring


Thank you for your kindly response @srmainwaring 

I was able to resolve issue that I mentioned by applying the instructions in [this link](https://discuss.ardupilot.org/t/ship-landing-global-position-init-forwarding/91339/12). I was not able to find the correct link you mentioned @srmainwaring 

In brief, as I understand, I have to send leader's gps position to follower vehicle. I did this via Mission Planner GCS (the link is above). Probably, the ` set posfwd 1` step also do same thing with I did. If I'm wrong, I would really appreciate it if you corrected me.

**Comment by timtuxworth** [comment]
> > I have same issue with @YonggilKwon . (Ship: No beacon)
> > I am trying to solve.
> 
> > > MAV> set posfwd 1
> > 
> > 
> > I could not understand this. How can I complete this step @srmainwaring
> 
> Thank you for your kindly response @srmainwaring
> 
> I was able to resolve issue that I mentioned by applying the instructions in [this link](https://discuss.ardupilot.org/t/ship-landing-global-position-init-forwarding/91339/12). I was not able to find the correct link you mentioned @srmainwaring
> 
> In brief, as I understand, I have to send leader's gps position to follower vehicle. I did this via Mission Planner GCS (the link is above). Probably, the ` set posfwd 1` step also do same thing with I did. If I'm wrong, I would really appreciate it if you corrected me.

I've found that sending the lead vehicle telemetry via the GCS can be laggy and unreliable. A better answer is to send the telemetry directly. I used SIK Telemetry radios in the lead and follow vehicle which worked well. There might be other ways.

**Comment by MustafaSari1** [comment]
> > > I have same issue with @YonggilKwon . (Ship: No beacon)
> > > I am trying to solve.
> > 
> > 
> > > > MAV> set posfwd 1
> > > 
> > > 
> > > I could not understand this. How can I complete this step @srmainwaring
> > 
> > 
> > Thank you for your kindly response @srmainwaring
> > I was able to resolve issue that I mentioned by applying the instructions in [this link](https://discuss.ardupilot.org/t/ship-landing-global-position-init-forwarding/91339/12). I was not able to find the correct link you mentioned @srmainwaring
> > In brief, as I understand, I have to send leader's gps position to follower vehicle. I did this via Mission Planner GCS (the link is above). Probably, the ` set posfwd 1` step also do same thing with I did. If I'm wrong, I would really appreciate it if you corrected me.
> 
> I've found that sending the lead vehicle telemetry via the GCS can be laggy and unreliable. A better answer is to send the telemetry directly. I used SIK Telemetry radios in the lead and follow vehicle which worked well. There might be other ways.

Could you please give some more information about your technique?

**Comment by MustafaSari1** [comment]
> > MAV> set posfwd 1
> 
> I could not understand this. How can I complete this step @srmainwaring

This command should be `set fwdpos 1`. Also, it is mentioned [here](https://github.com/ArduPilot/MissionPlanner/issues/2857).

**Pull request merged**
