### PR TITLE
Realflight add Paco-tailsitter

### PR DESCRIPTION
**Pull request by Quadzilla805**
Custom 3D frame tail sitter.
PACO-RF

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
This needs it parameter file updated to fix the tuning.  I'll help Brandon later fix the PR up later.

**Comment by Quadzilla805** [comment]
I found the correct parameter file and setup a new Pull request with all the updated files.

**Comment by Quadzilla805** [comment]
Also I setting up in WIP/Brandon....

**Comment by hendjoshsr71** [comment]
Closing in lieu of 

https://github.com/ArduPilot/SITL_Models/pull/90

**Pull request closed without merging**
